name: tweakin
main: baimo.minecraft.plugins.tweakin.Tweakin
version: '1.0'
api-version: '1.20'
author: baimo
description: 一个包含多个实用功能的插件
softdepend: [PlaceholderAPI]

commands:
  tweakin:
    description: 重新加载插件配置
    usage: /tweakin reload
    permission: tweakin.reload
    permission-message: §c你没有权限使用这个命令！

permissions:
  tweakin.reload:
    description: 允许重新加载插件配置
    default: op 